### ISSUE TITLE
Help me out!

### ISSUE THREAD

**Issue by erow80** [CodeLouisville/web-designer-proj-1#1]
@CodeLouisville/web-designer

If anyone would like to help me build this project out, let me know!

(Really just testing this out more than anything.)

![programmer](https://f.cloud.github.com/assets/1077169/2034341/6bac56fe-8929-11e3-9114-b9990c133a39.jpg)

**Comment by erow80** [comment]
Wow, this is old :) Closing.

**Comment by beckysteele** [comment]
Eric!

I tried to reach you during my first week with Code Louisville!  Let me
know if you get this!  I'd really like to touch base, since you're a CL
veteran and all!  Congrats on your move to the west coast!

Regards,
*Becky Steele*
*Project Coordinator*
<http://www.codelouisville.org>
*(502) 574-4395 <%28502%29%20574-2500>*

<https://www.facebook.com/codelouisville>
<https://twitter.com/codelouisville>
<https://www.linkedin.com/company/code-louisville>
<becky@codelouisville.org>
www.codelouisville.org

**Comment by erow80** [comment]
Sorry @beckysteele, I didn't get your other message! Hit me up at erow80@gmail.com if you want to discuss anything. Thanks!
